import { inngest } from "./inngest.client";
import { prisma } from "../index";
import { generateStoryWithGemini } from "./gemini.service";
import { generateImageFree } from "./image.service";
import { uploadToSupabase } from "./storage.service";
import { generateStoryPdf } from "./pdf.service";

export const generateStorybookWorkflow = inngest.createFunction(
  { id: "generate-storybook-workflow" },
  { event: "app/order.paid" },
  async ({ event, step }) => {
    const { orderId } = event.data;

    // 1. Update order status
    await step.run("update-order-processing", async () => {
      return await prisma.order.update({
        where: { id: orderId },
        data: { status: "PROCESSING" },
      });
    });

    const order = await prisma.order.findUnique({
      where: { id: orderId },
      include: { assets: { where: { type: "UPLOAD" } } },
    });

    if (!order) throw new Error("Order not found");

    // 2. Generate Story Script with Gemini
    const script = await step.run("generate-script-gemini", async () => {
      const imageUrls = order.assets.map((a) => a.url);
      return await generateStoryWithGemini(order.theme || "Magic Forest", imageUrls);
    });

    // 3. Generate Images
    const pagesWithImages = [];

    for (const [index, page] of script.pages.entries()) {
      const pageData = await step.run(`generate-page-image-${index}`, async () => {
        // Use the consistent prompt generated by Gemini
        const imageUrl = await generateImageFree(page.imagePrompt);
        const supabaseUrl = await uploadToSupabase(imageUrl, `page-${index}.png`);
        
        await prisma.asset.create({
          data: {
            orderId: order.id,
            url: supabaseUrl,
            type: "GENERATED",
          },
        });

        return { ...page, imageUrl: supabaseUrl };
      });
      pagesWithImages.push(pageData);
    }

    // 4. Create PDF and Finalize
    await step.run("generate-pdf-and-finalize", async () => {
      const pdfBuffer = await generateStoryPdf(script.title, pagesWithImages);
      const pdfUrl = await uploadToSupabase(pdfBuffer, "storybook.pdf", "storybooks");

      await prisma.storyBook.create({
        data: {
          orderId: order.id,
          title: script.title,
          content: pagesWithImages as any,
          pdfUrl: pdfUrl,
        },
      });

      await prisma.order.update({
        where: { id: orderId },
        data: { status: "COMPLETED" },
      });

      return { pdfUrl };
    });

    return { message: "Storybook generated successfully with Gemini" };
  }
);
